import { Email, CalendarEvent, JiraIssue } from '../core/types';

/**
 * Realistic mock data simulating a typical day at Scandicommerce.
 * Used by `chrisva demo` to show how the VA works without live credentials.
 */

const today = new Date();
function todayAt(hour: number, min = 0): Date {
  return new Date(today.getFullYear(), today.getMonth(), today.getDate(), hour, min);
}
function hoursAgo(h: number): Date {
  return new Date(Date.now() - h * 60 * 60 * 1000);
}

// ─── Emails ──────────────────────────────────────────
export const mockEmails: Email[] = [
  {
    id: 'mail-001',
    from: 'jan.devries@fashionstore.nl',
    to: ['chris@scandicommerce.com'],
    subject: 'URGENT: Checkout broken — customers cannot complete orders!',
    body: 'Hi Chris, since this morning our checkout is completely broken. Customers get a 500 error when they click "Place Order". This is critical — we are losing revenue every minute. Our store is fashionstore.nl. Please help ASAP!',
    snippet: 'Checkout broken, customers get 500 error on Place Order...',
    date: hoursAgo(1),
    isRead: false,
    labels: [],
    threadId: 'thread-001',
    importance: 'high',
    hasAttachments: false,
    conversationId: 'conv-001',
  },
  {
    id: 'mail-002',
    from: 'maria@homegoods-online.de',
    to: ['chris@scandicommerce.com'],
    subject: 'Payment provider integration not working after update',
    body: 'Hello Chris, after the latest platform update, our Mollie payment integration stopped working. We are a large merchant with 2000+ orders/day. Customers see "payment method unavailable". Can your team look into this urgently?',
    snippet: 'Mollie payment integration broken after platform update...',
    date: hoursAgo(2),
    isRead: false,
    labels: [],
    threadId: 'thread-002',
    importance: 'high',
    hasAttachments: true,
    conversationId: 'conv-002',
  },
  {
    id: 'mail-003',
    from: 'peter.bakker@scandicommerce.com',
    to: ['chris@scandicommerce.com'],
    subject: 'Sprint planning notes + action items',
    body: 'Hi Chris, here are the notes from yesterday\'s sprint planning. Key items: 1) Catalog search reindex scheduled for Thursday, 2) New merchant onboarding pipeline needs review, 3) Performance budget discussion Friday. Let me know if I missed anything.',
    snippet: 'Sprint planning notes and action items from yesterday...',
    date: hoursAgo(3),
    isRead: false,
    labels: [],
    threadId: 'thread-003',
    importance: 'normal',
    hasAttachments: false,
    conversationId: 'conv-003',
  },
  {
    id: 'mail-004',
    from: 'sophie@greenleaf-shop.com',
    to: ['chris@scandicommerce.com'],
    subject: 'Question about product import — CSV format',
    body: 'Hi Chris, we are trying to import our product catalog but keep getting format errors. The CSV has 5000 products. Could someone help us with the correct format? We\'d like to launch our store next week. Thanks!',
    snippet: 'Product import CSV format errors, 5000 products to import...',
    date: hoursAgo(4),
    isRead: false,
    labels: [],
    threadId: 'thread-004',
    importance: 'normal',
    hasAttachments: true,
    conversationId: 'conv-004',
  },
  {
    id: 'mail-005',
    from: 'noreply@atlassian.net',
    to: ['chris@scandicommerce.com'],
    subject: '[JIRA] SC-892 has been updated',
    body: 'Bob commented on SC-892: "Fixed the memory leak in the search indexer. Ready for review."',
    snippet: 'Bob commented on SC-892: Fixed the memory leak in the search indexer...',
    date: hoursAgo(4),
    isRead: false,
    labels: [],
    threadId: 'thread-005',
    importance: 'low',
    hasAttachments: false,
    conversationId: 'conv-005',
  },
  {
    id: 'mail-006',
    from: 'lars.nielsen@luxurybrands.dk',
    to: ['chris@scandicommerce.com'],
    subject: 'New merchant onboarding — LuxuryBrands Denmark',
    body: 'Dear Chris, we spoke last week about onboarding our store to Scandicommerce. We have 800 SKUs and would like to integrate with our existing ERP (SAP). What are the next steps? We aim for a go-live in Q2.',
    snippet: 'New merchant onboarding discussion, 800 SKUs, SAP ERP integration...',
    date: hoursAgo(5),
    isRead: false,
    labels: [],
    threadId: 'thread-006',
    importance: 'normal',
    hasAttachments: false,
    conversationId: 'conv-006',
  },
  {
    id: 'mail-007',
    from: 'alerts@datadoghq.com',
    to: ['chris@scandicommerce.com'],
    subject: '[Alert] High error rate on checkout-service (>5%)',
    body: 'Alert triggered: checkout-service error rate exceeded 5% threshold. Current: 8.3%. Started at 07:45 UTC. Affected region: EU-West. Dashboard: https://app.datadoghq.com/dashboard/checkout',
    snippet: 'High error rate on checkout-service, 8.3%, started 07:45 UTC...',
    date: hoursAgo(1.5),
    isRead: false,
    labels: [],
    threadId: 'thread-007',
    importance: 'high',
    hasAttachments: false,
    conversationId: 'conv-007',
  },
  {
    id: 'mail-008',
    from: 'newsletter@techcrunch.com',
    to: ['chris@scandicommerce.com'],
    subject: 'TechCrunch Daily: AI Commerce Trends 2026',
    body: 'Today in tech: AI-powered commerce platforms see 40% growth...',
    snippet: 'AI Commerce Trends 2026, platform growth statistics...',
    date: hoursAgo(6),
    isRead: false,
    labels: ['category_promotions'],
    threadId: 'thread-008',
    importance: 'low',
    hasAttachments: false,
    conversationId: 'conv-008',
  },
  {
    id: 'mail-009',
    from: 'emma.virtanen@scandicommerce.com',
    to: ['chris@scandicommerce.com'],
    subject: 'Can we chat about the merchant dashboard redesign?',
    body: 'Hey Chris, I\'ve been working on the merchant dashboard redesign mockups. Would love to get your input before I share with the broader team. Are you free for 30 min today or tomorrow?',
    snippet: 'Merchant dashboard redesign mockups, requesting meeting...',
    date: hoursAgo(7),
    isRead: false,
    labels: [],
    threadId: 'thread-009',
    importance: 'normal',
    hasAttachments: false,
    conversationId: 'conv-009',
  },
  {
    id: 'mail-010',
    from: 'thomas@sportgear-pro.se',
    to: ['chris@scandicommerce.com'],
    subject: 'Inventory sync issue — stock showing wrong numbers',
    body: 'Hi team, our inventory sync seems off. Products that are sold out still show as in stock on the storefront. We had 15 orders for out-of-stock items yesterday. This is causing customer complaints. Can this be fixed quickly?',
    snippet: 'Inventory sync issue, sold out products showing as in stock...',
    date: hoursAgo(3),
    isRead: false,
    labels: [],
    threadId: 'thread-010',
    importance: 'normal',
    hasAttachments: false,
    conversationId: 'conv-010',
  },
  {
    id: 'mail-011',
    from: 'noreply@github.com',
    to: ['chris@scandicommerce.com'],
    subject: '[scandicommerce/platform] PR #1247: Fix race condition in cart service',
    body: 'Alice opened a pull request: Fix race condition in cart service that caused duplicate line items.',
    snippet: 'PR #1247: Fix race condition in cart service...',
    date: hoursAgo(5),
    isRead: false,
    labels: [],
    threadId: 'thread-011',
    importance: 'low',
    hasAttachments: false,
    conversationId: 'conv-011',
  },
  {
    id: 'mail-012',
    from: 'procurement@scandicommerce.com',
    to: ['chris@scandicommerce.com'],
    subject: 'License renewal reminder — Datadog Enterprise',
    body: 'Hi Chris, the Datadog Enterprise license renews on March 1. Current cost: EUR 4,200/month. Please confirm if we want to continue or adjust the plan.',
    snippet: 'Datadog Enterprise license renewal March 1, EUR 4200/month...',
    date: hoursAgo(8),
    isRead: false,
    labels: [],
    threadId: 'thread-012',
    importance: 'normal',
    hasAttachments: false,
    conversationId: 'conv-012',
  },
];

// ─── Calendar Events ─────────────────────────────────
export const mockCalendarEvents: CalendarEvent[] = [
  {
    id: 'cal-001',
    subject: 'Daily Standup',
    start: todayAt(9, 15),
    end: todayAt(9, 30),
    location: '',
    isAllDay: false,
    organizer: 'peter.bakker@scandicommerce.com',
    attendees: ['chris@scandicommerce.com', 'alice@scandicommerce.com', 'bob@scandicommerce.com', 'carol@scandicommerce.com'],
    isOnline: true,
    onlineUrl: 'https://teams.microsoft.com/meet/standup',
    status: 'busy',
    body: 'Daily standup — what you did, what you\'re doing, blockers.',
  },
  {
    id: 'cal-002',
    subject: 'Merchant Escalation Review',
    start: todayAt(10, 0),
    end: todayAt(10, 30),
    location: 'Meeting Room 3A',
    isAllDay: false,
    organizer: 'chris@scandicommerce.com',
    attendees: ['chris@scandicommerce.com', 'emma.virtanen@scandicommerce.com'],
    isOnline: true,
    onlineUrl: 'https://teams.microsoft.com/meet/escalation',
    status: 'busy',
    body: 'Review open merchant escalations and assign action items.',
  },
  {
    id: 'cal-003',
    subject: 'Lunch with Product Team',
    start: todayAt(12, 0),
    end: todayAt(13, 0),
    location: 'Cafeteria',
    isAllDay: false,
    organizer: 'emma.virtanen@scandicommerce.com',
    attendees: ['chris@scandicommerce.com', 'emma.virtanen@scandicommerce.com', 'peter.bakker@scandicommerce.com'],
    isOnline: false,
    onlineUrl: '',
    status: 'busy',
    body: 'Informal lunch to discuss Q2 roadmap.',
  },
  {
    id: 'cal-004',
    subject: 'Architecture Review: New Search Infrastructure',
    start: todayAt(14, 0),
    end: todayAt(15, 0),
    location: '',
    isAllDay: false,
    organizer: 'bob@scandicommerce.com',
    attendees: ['chris@scandicommerce.com', 'bob@scandicommerce.com', 'dave@scandicommerce.com', 'carol@scandicommerce.com'],
    isOnline: true,
    onlineUrl: 'https://teams.microsoft.com/meet/arch-review',
    status: 'busy',
    body: 'Review the proposed Elasticsearch to OpenSearch migration plan.',
  },
  {
    id: 'cal-005',
    subject: '1:1 with Peter (Manager)',
    start: todayAt(16, 0),
    end: todayAt(16, 30),
    location: '',
    isAllDay: false,
    organizer: 'peter.bakker@scandicommerce.com',
    attendees: ['chris@scandicommerce.com', 'peter.bakker@scandicommerce.com'],
    isOnline: true,
    onlineUrl: 'https://teams.microsoft.com/meet/1on1',
    status: 'busy',
    body: 'Weekly 1:1 — discuss progress, blockers, career development.',
  },
];

// ─── Jira Issues (my open issues) ────────────────────
export const mockMyIssues: JiraIssue[] = [
  {
    key: 'SC-901',
    summary: 'Investigate checkout 500 errors reported by merchants',
    description: 'Multiple merchants reporting 500 errors during checkout flow. Correlated with recent deployment. Need to identify root cause.',
    status: 'In Progress',
    priority: 'Highest',
    assignee: 'Chris',
    reporter: 'Peter Bakker',
    created: hoursAgo(2),
    updated: hoursAgo(1),
    labels: ['production', 'checkout', 'merchant-impacting'],
    issueType: 'Bug',
    projectKey: 'SC',
  },
  {
    key: 'SC-887',
    summary: 'Review and approve search reindex migration plan',
    description: 'Review Dave\'s migration plan for moving from Elasticsearch 7 to OpenSearch. Need to sign off before Thursday implementation.',
    status: 'To Do',
    priority: 'High',
    assignee: 'Chris',
    reporter: 'Dave',
    created: hoursAgo(48),
    updated: hoursAgo(24),
    labels: ['search', 'infrastructure'],
    issueType: 'Task',
    projectKey: 'SC',
  },
  {
    key: 'SC-875',
    summary: 'Write merchant onboarding automation specs',
    description: 'Define the technical specifications for automating the merchant onboarding pipeline. Include API design, validation rules, and rollback procedures.',
    status: 'In Progress',
    priority: 'Medium',
    assignee: 'Chris',
    reporter: 'Emma Virtanen',
    created: hoursAgo(120),
    updated: hoursAgo(24),
    labels: ['onboarding', 'automation'],
    issueType: 'Story',
    projectKey: 'SC',
  },
  {
    key: 'SC-892',
    summary: 'Code review: Search indexer memory leak fix',
    description: 'Bob found and fixed a memory leak in the search indexer. Needs code review before merge.',
    status: 'In Review',
    priority: 'Medium',
    assignee: 'Chris',
    reporter: 'Bob',
    created: hoursAgo(72),
    updated: hoursAgo(4),
    labels: ['search', 'performance'],
    issueType: 'Bug',
    projectKey: 'SC',
  },
];

// ─── Jira Issues (unassigned — need triage) ──────────
export const mockUnassignedIssues: JiraIssue[] = [
  {
    key: 'SC-903',
    summary: 'Merchant: FashionStore checkout returning 500 errors',
    description: 'Merchant fashionstore.nl reports checkout is completely broken. Customers see 500 error. Likely related to the deployment from this morning. Merchant losing revenue.',
    status: 'Open',
    priority: 'Highest',
    assignee: null,
    reporter: 'Chris',
    created: hoursAgo(1),
    updated: hoursAgo(1),
    labels: ['merchant', 'checkout', 'production'],
    issueType: 'Bug',
    projectKey: 'SC',
  },
  {
    key: 'SC-904',
    summary: 'Merchant: Mollie payment integration broken after update',
    description: 'Merchant homegoods-online.de (2000+ orders/day) reports Mollie payments stopped working. "Payment method unavailable" error. Started after latest platform update.',
    status: 'Open',
    priority: 'Highest',
    assignee: null,
    reporter: 'Chris',
    created: hoursAgo(2),
    updated: hoursAgo(2),
    labels: ['merchant', 'payments', 'integration'],
    issueType: 'Bug',
    projectKey: 'SC',
  },
  {
    key: 'SC-905',
    summary: 'Merchant: Inventory sync showing wrong stock numbers',
    description: 'Merchant sportgear-pro.se reports inventory is not syncing correctly. Products sold out are still shown as available. 15 orders for out-of-stock items yesterday.',
    status: 'Open',
    priority: 'High',
    assignee: null,
    reporter: 'Chris',
    created: hoursAgo(3),
    updated: hoursAgo(3),
    labels: ['merchant', 'inventory', 'sync'],
    issueType: 'Bug',
    projectKey: 'SC',
  },
  {
    key: 'SC-906',
    summary: 'Support merchant with product catalog CSV import',
    description: 'Merchant greenleaf-shop.com needs help importing 5000 product catalog via CSV. Getting format errors. Aiming to launch next week.',
    status: 'Open',
    priority: 'Medium',
    assignee: null,
    reporter: 'Chris',
    created: hoursAgo(4),
    updated: hoursAgo(4),
    labels: ['merchant', 'onboarding', 'catalog'],
    issueType: 'Task',
    projectKey: 'SC',
  },
  {
    key: 'SC-907',
    summary: 'New merchant onboarding: LuxuryBrands Denmark (SAP ERP)',
    description: 'New merchant LuxuryBrands Denmark wants to onboard with 800 SKUs and SAP ERP integration. Go-live target Q2. Need to scope integration effort.',
    status: 'Open',
    priority: 'Medium',
    assignee: null,
    reporter: 'Chris',
    created: hoursAgo(5),
    updated: hoursAgo(5),
    labels: ['merchant', 'onboarding', 'erp-integration'],
    issueType: 'Story',
    projectKey: 'SC',
  },
  {
    key: 'SC-908',
    summary: 'Upgrade CI/CD pipeline to use GitHub Actions v4',
    description: 'Current CI pipeline uses deprecated GitHub Actions v3 runners. Need to upgrade before March deadline.',
    status: 'Open',
    priority: 'Low',
    assignee: null,
    reporter: 'Carol',
    created: hoursAgo(72),
    updated: hoursAgo(48),
    labels: ['ci-cd', 'infrastructure', 'maintenance'],
    issueType: 'Task',
    projectKey: 'SC',
  },
  {
    key: 'SC-909',
    summary: 'Add accessibility audit to merchant dashboard',
    description: 'Run WCAG 2.1 AA audit on the merchant dashboard and fix critical issues. Required for compliance with EU accessibility directive.',
    status: 'Open',
    priority: 'Medium',
    assignee: null,
    reporter: 'Eve',
    created: hoursAgo(96),
    updated: hoursAgo(48),
    labels: ['frontend', 'accessibility', 'compliance'],
    issueType: 'Story',
    projectKey: 'SC',
  },
];
